name: Subtree

on:
  workflow_dispatch:

jobs:
  subtree:
    name: Subtree
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Add deploykey
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          eval `ssh-agent -s`
          ssh-add - <<< '${{ secrets.DEPLOY_KEY }}'
          ssh -T git@github.com
        shell: bash

      - name: Subtree Pull
        shell: bash
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          git subtree pull --prefix .github/workflows git@github.com:MSpreckelsQS/subtree-sub.git main --squash

      - name: Create PR
        shell: bash
        run: |
          git checkout -b update-workflows

      - name: create pull request
        run: gh pr create -B main -H update-workflows --title 'Update GitHub Workflows' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}